.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "U2B" "1" "May 2015" "" ""
.
.SH "NAME"
\fBu2b\fR \-\- YouTube search, download, info and playback
.
.SH "USAGE"
 u2b [options] <command> <term>
.
.P
 u2b <id>     # Print page URL, thumbnail URL and title of video id
 u2b u <id>   # Print URL of stream for video id
 u2b a <id>   # All info on all streams for video id
 u2b d <id>   # Download video id
 u2b m <id>   # Play video id via mplayer
 u2b s Foo    # Print info about search hits for Foo
 u2b 0s Foo   # Print info about 1st search hit for Foo
 u2b u0s Foo  # Print URL of stream for 1st search hit for Foo
 u2b d1s Foo  # Download 2nd search hit for Foo
 u2b m12s Foo # Play 13th search hit for Foo
.
.SH "DESCRIPTION"
Fast YouTube search, download, stream\-URL extractor and playback utility\.
Playback is pluggable via config files\.
.
.P
The command has 3 optional parts:
 \- one letter verb, just print info if omitted
 \- number for selection from search hits, when using a search
 \- s for search
.
.P
The term is either a YouTube video link, a video id, or a search term,
the rest of the arguments is considered part of the search term\.
.
.SH "VERBS"
 u: extract best quality directly playable stream URL
 a: all info on all streams for video id
 d: download video, name it after 11\-letter id
 l: play video via omxplayer \-olocal
 h: play video via omxplayer \-ohdmi
 I: play video via omxd I (default omxd audio output)
 J: play video via omxd J (jack)
 H: play video via omxd H (HDMI)
 m: play video via mplayer
.
.P
All upper/lowercase letters except u, a, d can be mapped to different players
via config files /etc/u2b\.yml, ~/\.u2b\.yml or \.u2b\.yml\.
.
.SH "OPTIONS"
 \-f <format>  Choose print format from yaml (default), json, ini, html
 \-h           Print this help text and exit
 \-v           Show u2b version
\|\.